/*
* Copyright 2011 NTT Software Corporation.
* All Rights Reserved.
*/
/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package jp.co.ntts.vhut.exception {

    import jp.co.ntts.vhut.util.Enum;

    [Bindable]
    [RemoteClass(alias="jp.co.ntts.vhut.exception.AbstractConflictException$EntryType")]
	/**
	 * AbstractConflictException$EntryType Enum Class.
	 *
	 * <p>
	 * <b>Author :</b> NTT Software Corporation.
	 * <b>Version :</b> 1.0.0
	 * </p>
	 *
	 * @langversion 3.0
	 * @playerversion Flash 10.1
	 *
	 * @internal
	 * $Date$
	 * $Revision$
	 * $Author$
	 */
    public class AbstractConflictException$EntryType extends Enum {

        public static const CHANGED:AbstractConflictException$EntryType = new AbstractConflictException$EntryType("CHANGED", _);
        public static const REMOVED:AbstractConflictException$EntryType = new AbstractConflictException$EntryType("REMOVED", _);

        function AbstractConflictException$EntryType(value:String = null, restrictor:* = null) {
            super((value || CHANGED.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [CHANGED, REMOVED];
        }

        public static function valueOf(name:String):AbstractConflictException$EntryType {
            return AbstractConflictException$EntryType(CHANGED.constantOf(name));
        }
    }
}