/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package jp.co.ntts.vhut.exception {

    [Bindable]
    [RemoteClass(alias="jp.co.ntts.vhut.exception.InternalRuntimeException")]
	/**
	 * InternalRuntimeException Dto Class.
	 * <p></p>
	 * 
	 * <p>
	 * <b>Author :</b> NTT Software Corporation.
	 * <b>Version :</b> 1.0.0
	 * </p>
	 *
	 * @langversion 3.0
	 * @playerversion Flash 10.1
	 * 
	 * @internal
	 * $Date$
	 * $Revision$
	 * $Author$
	 */
    public class InternalRuntimeException extends InternalRuntimeExceptionBase {
    }
}