/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package jp.co.ntts.vhut.dto {
	import mx.resources.ResourceManager;

    [Bindable]
    [RemoteClass(alias="jp.co.ntts.vhut.dto.AdditionalDiskDto")]
	/**
	 * AdditionalDiskDto Dto Class.
	 * <p></p>
	 *
	 * <p>
	 * <b>Author :</b> NTT Software Corporation.
	 * <b>Version :</b> 1.0.0
	 * </p>
	 *
	 * @langversion 3.0
	 * @playerversion Flash 10.1
	 *
	 * @internal
	 * $Date: 2011-11-28 19:50:40 +0900 (月, 28 11 2011) $
	 * $Revision: 949 $
	 * $Author: NTT Software Corporation. $
	 */
    public class AdditionalDiskDto extends AdditionalDiskDtoBase {
		[SyncId]
		override public function get id():Number {
			return _id;
		}
		override public function set id(value:Number):void {
			_id = value;
		}

		[Transient]
		public function get name():String
		{
			if(!_name)
			{
				_name = ResourceManager.getInstance().getString("APIUI", "disk.additional");
			}
			return _name;
		}
		protected var _name:String;
    }
}