/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package jp.co.ntts.vhut.entity {

    import jp.co.ntts.vhut.util.Enum;

    [Bindable]
    [RemoteClass(alias="jp.co.ntts.vhut.entity.ApplicationInstanceGroupStatus")]
    public class ApplicationInstanceGroupStatus extends Enum {

        public static const NONE:ApplicationInstanceGroupStatus = new ApplicationInstanceGroupStatus("NONE", _);
        public static const CREATING:ApplicationInstanceGroupStatus = new ApplicationInstanceGroupStatus("CREATING", _);
        public static const DEACTIVE:ApplicationInstanceGroupStatus = new ApplicationInstanceGroupStatus("DEACTIVE", _);
        public static const ACTIVE:ApplicationInstanceGroupStatus = new ApplicationInstanceGroupStatus("ACTIVE", _);
        public static const DELETING:ApplicationInstanceGroupStatus = new ApplicationInstanceGroupStatus("DELETING", _);

        function ApplicationInstanceGroupStatus(value:String = null, restrictor:* = null) {
            super((value || NONE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [NONE, CREATING, DEACTIVE, ACTIVE, DELETING];
        }

        public static function valueOf(name:String):ApplicationInstanceGroupStatus {
            return ApplicationInstanceGroupStatus(NONE.constantOf(name));
        }
    }
}