/*
* Copyright 2011 NTT Software Corporation.
* All Rights Reserved.
*/
/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package jp.co.ntts.vhut.entity {

    import jp.co.ntts.vhut.util.Enum;

    [Bindable]
    [RemoteClass(alias="jp.co.ntts.vhut.entity.CommandStatus")]
	/**
	 * CommandStatus Enum Class.
	 *
	 * <p>
	 * <b>Author :</b> NTT Software Corporation.
	 * <b>Version :</b> 1.0.0
	 * </p>
	 *
	 * @langversion 3.0
	 * @playerversion Flash 10.1
	 *
	 * @internal
	 * $Date: 2011-11-28 19:50:40 +0900 (月, 28 11 2011) $
	 * $Revision: 949 $
	 * $Author: NTT Software Corporation. $
	 */
    public class CommandStatus extends Enum {

        public static const WAITING:CommandStatus = new CommandStatus("WAITING", _);
        public static const EXECUTING:CommandStatus = new CommandStatus("EXECUTING", _);
        public static const SUCCESS:CommandStatus = new CommandStatus("SUCCESS", _);
        public static const ERROR:CommandStatus = new CommandStatus("ERROR", _);
        public static const CANCELED:CommandStatus = new CommandStatus("CANCELED", _);
        public static const UNKNOWN:CommandStatus = new CommandStatus("UNKNOWN", _);

        function CommandStatus(value:String = null, restrictor:* = null) {
            super((value || WAITING.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [WAITING, EXECUTING, SUCCESS, ERROR, CANCELED, UNKNOWN];
        }

        public static function valueOf(name:String):CommandStatus {
            return CommandStatus(WAITING.constantOf(name));
        }
    }
}