/*
* Copyright 2011 NTT Software Corporation.
* All Rights Reserved.
*/
/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package jp.co.ntts.vhut.entity {

    import jp.co.ntts.vhut.util.Enum;

    [Bindable]
    [RemoteClass(alias="jp.co.ntts.vhut.entity.NetworkStatus")]
	/**
	 * NetworkStatus Enum Class.
	 *
	 * <p>
	 * <b>Author :</b> NTT Software Corporation.
	 * <b>Version :</b> 1.0.0
	 * </p>
	 *
	 * @langversion 3.0
	 * @playerversion Flash 10.1
	 *
	 * @internal
	 * $Date: 2011-11-28 19:50:40 +0900 (月, 28 11 2011) $
	 * $Revision: 949 $
	 * $Author: NTT Software Corporation. $
	 */
    public class NetworkStatus extends Enum {

        public static const AVAILABLE:NetworkStatus = new NetworkStatus("AVAILABLE", _);
        public static const ERROR:NetworkStatus = new NetworkStatus("ERROR", _);
        public static const UNKNOWN:NetworkStatus = new NetworkStatus("UNKNOWN", _);
        public static const RESERVED_BY_SYSTEM:NetworkStatus = new NetworkStatus("RESERVED_BY_SYSTEM", _);

        function NetworkStatus(value:String = null, restrictor:* = null) {
            super((value || AVAILABLE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [AVAILABLE, ERROR, UNKNOWN, RESERVED_BY_SYSTEM];
        }

        public static function valueOf(name:String):NetworkStatus {
            return NetworkStatus(AVAILABLE.constantOf(name));
        }
    }
}