/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package jp.co.ntts.vhut.entity {
	import jp.co.ntts.vhut.exception.NotJoinedRuntimeExceptionBase;

    [Bindable]
    [RemoteClass(alias="jp.co.ntts.vhut.entity.NotJoinedRuntimeException")]
    public class NotJoinedRuntimeException extends NotJoinedRuntimeExceptionBase {
    }
}