/*
* Copyright 2011 NTT Software Corporation.
* All Rights Reserved.
*/
/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package jp.co.ntts.vhut.entity {

    import jp.co.ntts.vhut.util.Enum;

    [Bindable]
    [RemoteClass(alias="jp.co.ntts.vhut.entity.ReleasedApplicationStatus")]
	/**
	 * ReleasedApplicationStatus Enum Class.
	 *
	 * <p>
	 * <b>Author :</b> NTT Software Corporation.
	 * <b>Version :</b> 1.0.0
	 * </p>
	 *
	 * @langversion 3.0
	 * @playerversion Flash 10.1
	 *
	 * @internal
	 * $Date: 2011-11-28 19:50:40 +0900 (月, 28 11 2011) $
	 * $Revision: 949 $
	 * $Author: NTT Software Corporation. $
	 */
    public class ReleasedApplicationStatus extends Enum {

        public static const NONE:ReleasedApplicationStatus = new ReleasedApplicationStatus("NONE", _);
        public static const CREATING:ReleasedApplicationStatus = new ReleasedApplicationStatus("CREATING", _);
        public static const READY:ReleasedApplicationStatus = new ReleasedApplicationStatus("READY", _);
        public static const DELETING:ReleasedApplicationStatus = new ReleasedApplicationStatus("DELETING", _);
        public static const DELETED:ReleasedApplicationStatus = new ReleasedApplicationStatus("DELETED", _);

        function ReleasedApplicationStatus(value:String = null, restrictor:* = null) {
            super((value || NONE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [NONE, CREATING, READY, DELETING, DELETED];
        }

        public static function valueOf(name:String):ReleasedApplicationStatus {
            return ReleasedApplicationStatus(NONE.constantOf(name));
        }
    }
}