/*
* Copyright 2011 NTT Software Corporation.
* All Rights Reserved.
*/
/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package jp.co.ntts.vhut.entity {

    import jp.co.ntts.vhut.util.Enum;

    [Bindable]
    [RemoteClass(alias="jp.co.ntts.vhut.entity.Right")]
	/**
	 * Right Enum Class.
	 *
	 * <p>
	 * <b>Author :</b> NTT Software Corporation.
	 * <b>Version :</b> 1.0.0
	 * </p>
	 *
	 * @langversion 3.0
	 * @playerversion Flash 10.1
	 *
	 * @internal
	 * $Date: 2011-11-28 19:50:40 +0900 (月, 28 11 2011) $
	 * $Revision: 949 $
	 * $Author: NTT Software Corporation. $
	 */
    public class Right extends Enum {

        public static const READ_SYS_BASIC:Right = new Right("READ_SYS_BASIC", _);
        public static const READ_OWN_APP:Right = new Right("READ_OWN_APP", _);
        public static const POWER_OWN_APP:Right = new Right("POWER_OWN_APP", _);
        public static const DISPLAY_OWN_APP:Right = new Right("DISPLAY_OWN_APP", _);
        public static const COMMAND_OWN_APP:Right = new Right("COMMAND_OWN_APP", _);
        public static const STATUS_OWN_APP:Right = new Right("STATUS_OWN_APP", _);
        public static const TERM_OWN_APP:Right = new Right("TERM_OWN_APP", _);
        public static const UPDATE_OWN_APP:Right = new Right("UPDATE_OWN_APP", _);
        public static const CREATE_OWN_APP:Right = new Right("CREATE_OWN_APP", _);
        public static const DELETE_OWN_APP:Right = new Right("DELETE_OWN_APP", _);
        public static const READ_ALL_APP:Right = new Right("READ_ALL_APP", _);
        public static const POWER_ALL_APP:Right = new Right("POWER_ALL_APP", _);
        public static const DISPLAY_ALL_APP:Right = new Right("DISPLAY_ALL_APP", _);
        public static const COMMAND_ALL_APP:Right = new Right("COMMAND_ALL_APP", _);
        public static const STATUS_ALL_APP:Right = new Right("STATUS_ALL_APP", _);
        public static const TERM_ALL_APP:Right = new Right("TERM_ALL_APP", _);
        public static const UPDATE_ALL_APP:Right = new Right("UPDATE_ALL_APP", _);
        public static const CREATE_ALL_APP:Right = new Right("CREATE_ALL_APP", _);
        public static const DELETE_ALL_APP:Right = new Right("DELETE_ALL_APP", _);
        public static const READ_ALL_RAPP:Right = new Right("READ_ALL_RAPP", _);
        public static const COMMAND_ALL_RAPP:Right = new Right("COMMAND_ALL_RAPP", _);
        public static const CREATE_ALL_RAPP:Right = new Right("CREATE_ALL_RAPP", _);
        public static const DELETE_ALL_RAPP:Right = new Right("DELETE_ALL_RAPP", _);
        public static const READ_OWN_RAPP:Right = new Right("READ_OWN_RAPP", _);
        public static const COMMAND_OWN_RAPP:Right = new Right("COMMAND_OWN_RAPP", _);
        public static const CREATE_OWN_RAPP:Right = new Right("CREATE_OWN_RAPP", _);
        public static const DELETE_OWN_RAPP:Right = new Right("DELETE_OWN_RAPP", _);
        public static const READ_OWN_AIG:Right = new Right("READ_OWN_AIG", _);
        public static const UPDATE_OWN_AIG:Right = new Right("UPDATE_OWN_AIG", _);
        public static const CREATE_OWN_AIG:Right = new Right("CREATE_OWN_AIG", _);
        public static const DELETE_OWN_AIG:Right = new Right("DELETE_OWN_AIG", _);
        public static const READ_ALL_AIG:Right = new Right("READ_ALL_AIG", _);
        public static const UPDATE_ALL_AIG:Right = new Right("UPDATE_ALL_AIG", _);
        public static const CREATE_ALL_AIG:Right = new Right("CREATE_ALL_AIG", _);
        public static const DELETE_ALL_AIG:Right = new Right("DELETE_ALL_AIG", _);
        public static const READ_OWN_AI:Right = new Right("READ_OWN_AI", _);
        public static const POWER_OWN_AI:Right = new Right("POWER_OWN_AI", _);
        public static const DISPLAY_OWN_AI:Right = new Right("DISPLAY_OWN_AI", _);
        public static const COMMAND_OWN_AI:Right = new Right("COMMAND_OWN_AI", _);
        public static const STATUS_OWN_AI:Right = new Right("STATUS_OWN_AI", _);
        public static const REBUILD_OWN_AI:Right = new Right("REBUILD_OWN_AI", _);
        public static const READ_CHILD_AI:Right = new Right("READ_CHILD_AI", _);
        public static const POWER_CHILD_AI:Right = new Right("POWER_CHILD_AI", _);
        public static const DISPLAY_CHILD_AI:Right = new Right("DISPLAY_CHILD_AI", _);
        public static const COMMAND_CHILD_AI:Right = new Right("COMMAND_CHILD_AI", _);
        public static const STATUS_CHILD_AI:Right = new Right("STATUS_CHILD_AI", _);
        public static const REBUILD_CHILD_AI:Right = new Right("REBUILD_CHILD_AI", _);
        public static const READ_ALL_AI:Right = new Right("READ_ALL_AI", _);
        public static const POWER_ALL_AI:Right = new Right("POWER_ALL_AI", _);
        public static const DISPLAY_ALL_AI:Right = new Right("DISPLAY_ALL_AI", _);
        public static const COMMAND_ALL_AI:Right = new Right("COMMAND_ALL_AI", _);
        public static const STATUS_ALL_AI:Right = new Right("STATUS_ALL_AI", _);
        public static const REBUILD_ALL_AI:Right = new Right("REBUILD_ALL_AI", _);
        public static const READ_SYS_TEMPLATE:Right = new Right("READ_SYS_TEMPLATE", _);
        public static const UPDATE_SYS_TEMPLATE:Right = new Right("UPDATE_SYS_TEMPLATE", _);
        public static const CREATE_SYS_TEMPLATE:Right = new Right("CREATE_SYS_TEMPLATE", _);
        public static const DELETE_SYS_TEMPLATE:Right = new Right("DELETE_SYS_TEMPLATE", _);
        public static const READ_SYS_ROLE:Right = new Right("READ_SYS_ROLE", _);
        public static const UPDATE_SYS_ROLE:Right = new Right("UPDATE_SYS_ROLE", _);
        public static const CREATE_SYS_ROLE:Right = new Right("CREATE_SYS_ROLE", _);
        public static const DELETE_SYS_ROLE:Right = new Right("DELETE_SYS_ROLE", _);
        public static const READ_OWN_USER:Right = new Right("READ_OWN_USER", _);
        public static const UPDATE_OWN_USER:Right = new Right("UPDATE_OWN_USER", _);
        public static const READ_ALL_USER:Right = new Right("READ_ALL_USER", _);
        public static const UPDATE_ALL_USER:Right = new Right("UPDATE_ALL_USER", _);
        public static const CREATE_ALL_USER:Right = new Right("CREATE_ALL_USER", _);
        public static const DELETE_ALL_USER:Right = new Right("DELETE_ALL_USER", _);
        public static const READ_SYS_MANAGEMENT:Right = new Right("READ_SYS_MANAGEMENT", _);
        public static const READ_SYS_CONFIGURATION:Right = new Right("READ_SYS_CONFIGURATION", _);
        public static const UPDATE_SYS_CONFIGURATION:Right = new Right("UPDATE_SYS_CONFIGURATION", _);

        function Right(value:String = null, restrictor:* = null) {
            super((value || READ_SYS_BASIC.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [READ_SYS_BASIC, READ_OWN_APP, POWER_OWN_APP, DISPLAY_OWN_APP, COMMAND_OWN_APP, STATUS_OWN_APP, TERM_OWN_APP, UPDATE_OWN_APP, CREATE_OWN_APP, DELETE_OWN_APP, READ_ALL_APP, POWER_ALL_APP, DISPLAY_ALL_APP, COMMAND_ALL_APP, STATUS_ALL_APP, TERM_ALL_APP, UPDATE_ALL_APP, CREATE_ALL_APP, DELETE_ALL_APP, READ_ALL_RAPP, COMMAND_ALL_RAPP, CREATE_ALL_RAPP, DELETE_ALL_RAPP, READ_OWN_RAPP, COMMAND_OWN_RAPP, CREATE_OWN_RAPP, DELETE_OWN_RAPP, READ_OWN_AIG, UPDATE_OWN_AIG, CREATE_OWN_AIG, DELETE_OWN_AIG, READ_ALL_AIG, UPDATE_ALL_AIG, CREATE_ALL_AIG, DELETE_ALL_AIG, READ_OWN_AI, POWER_OWN_AI, DISPLAY_OWN_AI, COMMAND_OWN_AI, STATUS_OWN_AI, REBUILD_OWN_AI, READ_CHILD_AI, POWER_CHILD_AI, DISPLAY_CHILD_AI, COMMAND_CHILD_AI, STATUS_CHILD_AI, REBUILD_CHILD_AI, READ_ALL_AI, POWER_ALL_AI, DISPLAY_ALL_AI, COMMAND_ALL_AI, STATUS_ALL_AI, REBUILD_ALL_AI, READ_SYS_TEMPLATE, UPDATE_SYS_TEMPLATE, CREATE_SYS_TEMPLATE, DELETE_SYS_TEMPLATE, READ_SYS_ROLE, UPDATE_SYS_ROLE, CREATE_SYS_ROLE, DELETE_SYS_ROLE, READ_OWN_USER, UPDATE_OWN_USER, READ_ALL_USER, UPDATE_ALL_USER, CREATE_ALL_USER, DELETE_ALL_USER, READ_SYS_MANAGEMENT, READ_SYS_CONFIGURATION, UPDATE_SYS_CONFIGURATION];
        }

        public static function valueOf(name:String):Right {
            return Right(READ_SYS_BASIC.constantOf(name));
        }
    }
}