/*
* Copyright 2011 NTT Software Corporation.
* All Rights Reserved.
*/
/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package jp.co.ntts.vhut.entity {

    import jp.co.ntts.vhut.util.Enum;

    [Bindable]
    [RemoteClass(alias="jp.co.ntts.vhut.entity.RightLevel")]
	/**
	 * RightLevel Enum Class.
	 *
	 * <p>
	 * <b>Author :</b> NTT Software Corporation.
	 * <b>Version :</b> 1.0.0
	 * </p>
	 *
	 * @langversion 3.0
	 * @playerversion Flash 10.1
	 *
	 * @internal
	 * $Date$
	 * $Revision$
	 * $Author$
	 */
    public class RightLevel extends Enum {

        public static const SYS:RightLevel = new RightLevel("SYS", _);
        public static const OWN:RightLevel = new RightLevel("OWN", _);
        public static const CHILD:RightLevel = new RightLevel("CHILD", _);
        public static const ALL:RightLevel = new RightLevel("ALL", _);

        function RightLevel(value:String = null, restrictor:* = null) {
            super((value || SYS.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [SYS, OWN, CHILD, ALL];
        }

        public static function valueOf(name:String):RightLevel {
            return RightLevel(SYS.constantOf(name));
        }
    }
}