/*
* Copyright 2011 NTT Software Corporation.
* All Rights Reserved.
*/
/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package jp.co.ntts.vhut.entity {

    import jp.co.ntts.vhut.util.Enum;

    [Bindable]
    [RemoteClass(alias="jp.co.ntts.vhut.entity.RightAction")]
	/**
	 * RightAction Enum Class.
	 *
	 * <p>
	 * <b>Author :</b> NTT Software Corporation.
	 * <b>Version :</b> 1.0.0
	 * </p>
	 *
	 * @langversion 3.0
	 * @playerversion Flash 10.1
	 *
	 * @internal
	 * $Date$
	 * $Revision$
	 * $Author$
	 */
    public class RightAction extends Enum {

        public static const READ:RightAction = new RightAction("READ", _);
        public static const POWER:RightAction = new RightAction("POWER", _);
        public static const DISPLAY:RightAction = new RightAction("DISPLAY", _);
        public static const COMMAND:RightAction = new RightAction("COMMAND", _);
        public static const STATUS:RightAction = new RightAction("STATUS", _);
        public static const TERM:RightAction = new RightAction("TERM", _);
        public static const UPDATE:RightAction = new RightAction("UPDATE", _);
        public static const CREATE:RightAction = new RightAction("CREATE", _);
        public static const DELETE:RightAction = new RightAction("DELETE", _);
        public static const REBUILD:RightAction = new RightAction("REBUILD", _);

        function RightAction(value:String = null, restrictor:* = null) {
            super((value || READ.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [READ, POWER, DISPLAY, COMMAND, STATUS, TERM, UPDATE, CREATE, DELETE, REBUILD];
        }

        public static function valueOf(name:String):RightAction {
            return RightAction(READ.constantOf(name));
        }
    }
}