/*
* Copyright 2011 NTT Software Corporation.
* All Rights Reserved.
*/
/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package jp.co.ntts.vhut.entity {

    import jp.co.ntts.vhut.util.Enum;

    [Bindable]
    [RemoteClass(alias="jp.co.ntts.vhut.entity.VmStatus")]
	/**
	 * VmStatus Enum Class.
	 *
	 * <p>
	 * <b>Author :</b> NTT Software Corporation.
	 * <b>Version :</b> 1.0.0
	 * </p>
	 *
	 * @langversion 3.0
	 * @playerversion Flash 10.1
	 *
	 * @internal
	 * $Date: 2011-11-28 19:50:40 +0900 (月, 28 11 2011) $
	 * $Revision: 949 $
	 * $Author: NTT Software Corporation. $
	 */
    public class VmStatus extends Enum {

        public static const DEVELOPPING:VmStatus = new VmStatus("DEVELOPPING", _);
        public static const DOWN:VmStatus = new VmStatus("DOWN", _);
        public static const POWERING_UP:VmStatus = new VmStatus("POWERING_UP", _);
        public static const UP:VmStatus = new VmStatus("UP", _);
        public static const UNAVAILABLE:VmStatus = new VmStatus("UNAVAILABLE", _);
        public static const SHUTTING_DOWN:VmStatus = new VmStatus("SHUTTING_DOWN", _);
        public static const ERROR:VmStatus = new VmStatus("ERROR", _);
        public static const UNKNOWN:VmStatus = new VmStatus("UNKNOWN", _);

        function VmStatus(value:String = null, restrictor:* = null) {
            super((value || DEVELOPPING.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [DEVELOPPING, DOWN, POWERING_UP, UP, UNAVAILABLE, SHUTTING_DOWN, ERROR, UNKNOWN];
        }

        public static function valueOf(name:String):VmStatus {
            return VmStatus(DEVELOPPING.constantOf(name));
        }
    }
}